type it up layout
skandertebo/type-it-up pull request #4
Opened 2024-12-31 02:04 UTC by Malek215

2025-01-01 19:21 UTC, MohamedRebai41 requested changes

2025-01-01 19:21 UTC, MohamedRebai41 commented on libs/frontend/type-it-up-home/src/lib/navbar/type-it-up-navbar-item/type-it-up-navbar-item.component.html
You don't have to add type-it-up to every file or folder name (keep it only for libs)

2025-01-01 19:21 UTC, MohamedRebai41 commented on libs/frontend/type-it-up-home/src/lib/navbar/type-it-up-navbar-item/type-it-up-navbar-item.component.ts
same for selector names, makes html code cluttered

2025-01-17 15:33 UTC, skandertebo requested changes

2025-01-17 15:33 UTC, skandertebo commented on apps/type-it-up/project.json
> +  }
please fix indentation

2025-01-17 15:33 UTC, skandertebo commented on libs/frontend/type-it-up-home/src/lib/type-it-up-home-layout/type-it-up-home-layout.component.ts
> +// }
remove this commented code

2025-01-20 14:53 UTC, skandertebo approved these changes

2025-01-20 14:53 UTC, skandertebo commented on libs/frontend/type-it-up-home/src/lib/type-it-up-home-layout/home-layout.component.html
> +  </div> -->
remove commented code

2025-01-20 15:01 UTC, merged